import dotenv from "dotenv";
import { Secret } from "jsonwebtoken";

dotenv.config();

interface NodeEnv {
  DATABASE_URL: string;
  PORT: string;
  GOOGLE_GENERATIVE_AI_API_KEY: string;
  JWT_TOKEN_ACCESS_SECRET: Secret;
  JWT_TOKEN_REFRESH_SECRET: Secret;
  ACCESS_TOKEN_EXPIRY: string;
  REFRESH_TOKEN_EXPIRY: string;
  CORS_ORIGIN: string;
}

const {
  DATABASE_URL,
  PORT,
  GOOGLE_GENERATIVE_AI_API_KEY,
  JWT_SECRET,
  JWT_TOKEN_REFRESH_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  CORS_ORIGIN,
} = process.env;

export const env: NodeEnv = {
  DATABASE_URL: DATABASE_URL!,
  PORT: PORT || "5000",
  GOOGLE_GENERATIVE_AI_API_KEY: GOOGLE_GENERATIVE_AI_API_KEY!,
  JWT_TOKEN_ACCESS_SECRET: JWT_SECRET!,
  JWT_TOKEN_REFRESH_SECRET: JWT_TOKEN_REFRESH_SECRET!,
  ACCESS_TOKEN_EXPIRY: ACCESS_TOKEN_EXPIRY!,
  REFRESH_TOKEN_EXPIRY: REFRESH_TOKEN_EXPIRY!,
  CORS_ORIGIN: CORS_ORIGIN!,
};
